### ISSUE TITLE
[BUG] Dashboard & Interfaces empty

### ISSUE THREAD

**Issue by jasondaigo** [cogwheel0/luci-mobile#46]
### App Version

1.1.8

### Platform

- [x] Android
- [ ] iOS

### How you installed it

IzzyOnDroid

### What happened?

Im not seeing any Data when logging in. In the Github readme you already had this covered under Troubleshooting but i dont understand what that means. Is there anything special i have to set on the router side for this app to work? This is a new OpenWrt x86-am64 install. I only have configured Internet access over pppoe, ddns and https port forward so far.

### What should have happened?

Metrics and Adapter shown

### How to reproduce

1. Login to OpenWrt Router
2. Click Dashboard or Interfaces

### Does this happen every time?

None

### When did this start?

Initial run

### Screenshots

<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/10662bc7-ab8b-4699-ad81-63f6d1eae373" />

<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/01a89109-0814-422c-86db-ac23aab19680" />

<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/909b7d13-4faf-4f9c-be03-49572d99a301" />

<img width="1177" height="632" alt="Image" src="https://github.com/user-attachments/assets/08cfe877-28a0-4a69-adaa-6d1e78621662" />

**Comment by cogwheel0** [comment]
@rendiix @jasondaigo I updated the README. Can you try the instructions?

https://github.com/cogwheel0/luci-mobile#troubleshooting

**Comment by MrNRod** [comment]
Hey @cogwheel0 

I was missing the luci-rpc package on my router. I installed the packages listed in the readme and restarted rpcd. Still not able to get the Dashboard and Interfaces page to load.

Here is the console output:

```
root@Lucid-RT:~# opkg update && opkg install luci-mod-rpc rpcd-mod-luci rpcd-mod-iwinfo luci-mod-status
Downloading https://downloads.openwrt.org/releases/24.10.3/targets/ramips/mt7621/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_core
Downloading https://downloads.openwrt.org/releases/24.10.3/targets/ramips/mt7621/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/24.10.3/packages/mipsel_24kc/base/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_base
Downloading https://downloads.openwrt.org/releases/24.10.3/packages/mipsel_24kc/base/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/24.10.3/targets/ramips/mt7621/kmods/6.6.104-1-ae7dcdf01cb63b83c64f5cb8d8960511/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_kmods
Downloading https://downloads.openwrt.org/releases/24.10.3/targets/ramips/mt7621/kmods/6.6.104-1-ae7dcdf01cb63b83c64f5cb8d8960511/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/24.10.3/packages/mipsel_24kc/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_luci
Downloading https://downloads.openwrt.org/releases/24.10.3/packages/mipsel_24kc/luci/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/24.10.3/packages/mipsel_24kc/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_packages
Downloading https://downloads.openwrt.org/releases/24.10.3/packages/mipsel_24kc/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/24.10.3/packages/mipsel_24kc/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_routing
Downloading https://downloads.openwrt.org/releases/24.10.3/packages/mipsel_24kc/routing/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/24.10.3/packages/mipsel_24kc/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_telephony
Downloading https://downloads.openwrt.org/releases/24.10.3/packages/mipsel_24kc/telephony/Packages.sig
Signature check passed.
Package luci-mod-rpc (25.273.68624~395e73d) installed in root is up to date.
Package rpcd-mod-luci (20240305-r1) installed in root is up to date.
Package rpcd-mod-iwinfo (2025.09.01~bba95191-r1) installed in root is up to date.
Package luci-mod-status (25.273.68624~395e73d) installed in root is up to date.
root@Lucid-RT:~# /etc/init.d/rpcd restart
root@Lucid-RT:~# ubus list luci-rpc
luci-rpc
root@Lucid-RT:~# ubus call luci-rpc getNetworkDevices '{}'
{
	"eth5": {
		"name": "eth5",
		"wireless": false,
		"up": true,
		"mtu": 1500,
		"qlen": 1000,
		"devtype": "dsa",
		"ipaddrs": [
			
		],
		"ip6addrs": [
			{
				"address": "fe80::be9a:8eff:feb7:b640",
				"netmask": "ffff:ffff:ffff:ffff::"
			}
		],
		"mac": "BC:9A:8E:B7:B6:40",
		"type": 1,
		"ifindex": 8,
		"parent": "dsa",
		"stats": {
			"rx_bytes": 2571918201,
			"tx_bytes": 1809897488,
			"tx_errors": 0,
			"rx_errors": 0,
			"tx_packets": 9955652,
			"rx_packets": 9254747,
			"multicast": 0,
			"collisions": 0,
			"rx_dropped": 0,
			"tx_dropped": 0
		},
		"flags": {
			"up": true,
			"broadcast": true,
			"promisc": false,
			"loopback": false,
			"noarp": false,
			"multicast": true,
			"pointtopoint": false
		},
		"link": {
			"speed": 1000,
			"duplex": "full",
			"carrier": true,
			"changes": 1,
			"up_count": 1,
			"down_count": 0
		}
	},
	"eth3": {
		"name": "eth3",
		"master": "br-lan",
		"wireless": false,
		"up": false,
		"mtu": 1500,
		"qlen": 1000,
		"devtype": "dsa",
		"ipaddrs": [
			
		],
		"ip6addrs": [
			
		],
		"mac": "AC:8B:A9:B9:79:B8",
		"type": 1,
		"ifindex": 6,
		"parent": "dsa",
		"stats": {
			"rx_bytes": 0,
			"tx_bytes": 0,
			"tx_errors": 0,
			"rx_errors": 0,
			"tx_packets": 0,
			"rx_packets": 0,
			"multicast": 0,
			"collisions": 0,
			"rx_dropped": 0,
			"tx_dropped": 0
		},
		"flags": {
			"up": true,
			"broadcast": true,
			"promisc": false,
			"loopback": false,
			"noarp": false,
			"multicast": true,
			"pointtopoint": false
		},
		"link": {
			"speed": -1,
			"duplex": "unknown",
			"carrier": false,
			"changes": 0,
			"up_count": 0,
			"down_count": 0
		}
	},
	"lo": {
		"name": "lo",
		"wireless": false,
		"up": true,
		"mtu": 65536,
		"qlen": 1000,
		"devtype": "ethernet",
		"ipaddrs": [
			{
				"address": "127.0.0.1",
				"netmask": "255.0.0.0"
			}
		],
		"ip6addrs": [
			{
				"address": "::1",
				"netmask": "ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff"
			}
		],
		"type": 772,
		"ifindex": 1,
		"stats": {
			"rx_bytes": 1175695,
			"tx_bytes": 1175695,
			"tx_errors": 0,
			"rx_errors": 0,
			"tx_packets": 10439,
			"rx_packets": 10439,
			"multicast": 0,
			"collisions": 0,
			"rx_dropped": 0,
			"tx_dropped": 0
		},
		"flags": {
			"up": true,
			"broadcast": false,
			"promisc": false,
			"loopback": true,
			"noarp": false,
			"multicast": false,
			"pointtopoint": false
		},
		"link": {
			"carrier": true,
			"changes": 0,
			"up_count": 0,
			"down_count": 0
		}
	},
	"eth1": {
		"name": "eth1",
		"master": "br-lan",
		"wireless": false,
		"up": true,
		"mtu": 1500,
		"qlen": 1000,
		"devtype": "dsa",
		"ipaddrs": [
			
		],
		"ip6addrs": [
			
		],
		"mac": "AC:8B:A9:B9:79:B6",
		"type": 1,
		"ifindex": 4,
		"parent": "dsa",
		"stats": {
			"rx_bytes": 48266183,
			"tx_bytes": 93140846,
			"tx_errors": 0,
			"rx_errors": 0,
			"tx_packets": 175256,
			"rx_packets": 211720,
			"multicast": 0,
			"collisions": 0,
			"rx_dropped": 0,
			"tx_dropped": 0
		},
		"flags": {
			"up": true,
			"broadcast": true,
			"promisc": false,
			"loopback": false,
			"noarp": false,
			"multicast": true,
			"pointtopoint": false
		},
		"link": {
			"speed": 100,
			"duplex": "full",
			"carrier": true,
			"changes": 23,
			"up_count": 12,
			"down_count": 11
		}
	},
	"dsa": {
		"name": "dsa",
		"wireless": false,
		"up": true,
		"mtu": 1504,
		"qlen": 1000,
		"devtype": "ethernet",
		"ipaddrs": [
			
		],
		"ip6addrs": [
			{
				"address": "fe80::ae8b:a9ff:feb9:79b5",
				"netmask": "ffff:ffff:ffff:ffff::"
			}
		],
		"mac": "AC:8B:A9:B9:79:B5",
		"type": 1,
		"ifindex": 2,
		"stats": {
			"rx_bytes": 148602429511,
			"tx_bytes": 148230845124,
			"tx_errors": 0,
			"rx_errors": 20,
			"tx_packets": 139084378,
			"rx_packets": 141713310,
			"multicast": 0,
			"collisions": 0,
			"rx_dropped": 0,
			"tx_dropped": 0
		},
		"flags": {
			"up": true,
			"broadcast": true,
			"promisc": false,
			"loopback": false,
			"noarp": false,
			"multicast": true,
			"pointtopoint": false
		},
		"link": {
			"speed": 1000,
			"duplex": "full",
			"carrier": true,
			"changes": 3,
			"up_count": 2,
			"down_count": 1
		}
	},
	"eth5.2": {
		"name": "eth5.2",
		"wireless": false,
		"up": true,
		"mtu": 1500,
		"qlen": 1000,
		"devtype": "vlan",
		"ipaddrs": [
			{
				"address": "REMOVED",
				"netmask": "255.255.252.0",
				"broadcast": "REMOVED
			}
		],
		"ip6addrs": [
			{
				"address": "REMOVED",
				"netmask": "ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff"
			},
			{
				"address": "fe80::be9a:8eff:feb7:b640",
				"netmask": "ffff:ffff:ffff:ffff::"
			}
		],
		"mac": "BC:9A:8E:B7:B6:40",
		"type": 1,
		"ifindex": 10,
		"parent": "eth5",
		"stats": {
			"rx_bytes": 273892717,
			"tx_bytes": 1770074082,
			"tx_errors": 0,
			"rx_errors": 0,
			"tx_packets": 9955645,
			"rx_packets": 1010259,
			"multicast": 0,
			"collisions": 0,
			"rx_dropped": 0,
			"tx_dropped": 0
		},
		"flags": {
			"up": true,
			"broadcast": true,
			"promisc": false,
			"loopback": false,
			"noarp": false,
			"multicast": true,
			"pointtopoint": false
		},
		"link": {
			"speed": 1000,
			"duplex": "full",
			"carrier": true,
			"changes": 1,
			"up_count": 1,
			"down_count": 0
		}
	},
	"eth4": {
		"name": "eth4",
		"master": "br-lan",
		"wireless": false,
		"up": false,
		"mtu": 1500,
		"qlen": 1000,
		"devtype": "dsa",
		"ipaddrs": [
			
		],
		"ip6addrs": [
			
		],
		"mac": "AC:8B:A9:B9:79:B9",
		"type": 1,
		"ifindex": 7,
		"parent": "dsa",
		"stats": {
			"rx_bytes": 0,
			"tx_bytes": 0,
			"tx_errors": 0,
			"rx_errors": 0,
			"tx_packets": 0,
			"rx_packets": 0,
			"multicast": 0,
			"collisions": 0,
			"rx_dropped": 0,
			"tx_dropped": 0
		},
		"flags": {
			"up": true,
			"broadcast": true,
			"promisc": false,
			"loopback": false,
			"noarp": false,
			"multicast": true,
			"pointtopoint": false
		},
		"link": {
			"speed": -1,
			"duplex": "unknown",
			"carrier": false,
			"changes": 0,
			"up_count": 0,
			"down_count": 0
		}
	},
	"eth2": {
		"name": "eth2",
		"master": "br-lan",
		"wireless": false,
		"up": true,
		"mtu": 1500,
		"qlen": 1000,
		"devtype": "dsa",
		"ipaddrs": [
			
		],
		"ip6addrs": [
			
		],
		"mac": "AC:8B:A9:B9:79:B7",
		"type": 1,
		"ifindex": 5,
		"parent": "dsa",
		"stats": {
			"rx_bytes": 8073748,
			"tx_bytes": 10857555,
			"tx_errors": 0,
			"rx_errors": 0,
			"tx_packets": 26209,
			"rx_packets": 29128,
			"multicast": 0,
			"collisions": 0,
			"rx_dropped": 81,
			"tx_dropped": 0
		},
		"flags": {
			"up": true,
			"broadcast": true,
			"promisc": false,
			"loopback": false,
			"noarp": false,
			"multicast": true,
			"pointtopoint": false
		},
		"link": {
			"speed": 1000,
			"duplex": "full",
			"carrier": true,
			"changes": 103,
			"up_count": 52,
			"down_count": 51
		}
	},
	"eth0": {
		"name": "eth0",
		"master": "br-lan",
		"wireless": false,
		"up": true,
		"mtu": 1500,
		"qlen": 1000,
		"devtype": "dsa",
		"ipaddrs": [
			
		],
		"ip6addrs": [
			
		],
		"mac": "AC:8B:A9:B9:79:B5",
		"type": 1,
		"ifindex": 3,
		"parent": "dsa",
		"stats": {
			"rx_bytes": 2228522609,
			"tx_bytes": 2484097852,
			"tx_errors": 0,
			"rx_errors": 0,
			"tx_packets": 9174784,
			"rx_packets": 12473888,
			"multicast": 0,
			"collisions": 0,
			"rx_dropped": 0,
			"tx_dropped": 0
		},
		"flags": {
			"up": true,
			"broadcast": true,
			"promisc": false,
			"loopback": false,
			"noarp": false,
			"multicast": true,
			"pointtopoint": false
		},
		"link": {
			"speed": 1000,
			"duplex": "full",
			"carrier": true,
			"changes": 1,
			"up_count": 1,
			"down_count": 0
		}
	},
	"br-lan": {
		"name": "br-lan",
		"bridge": true,
		"ports": [
			"eth0",
			"eth3",
			"eth1",
			"eth4",
			"eth2"
		],
		"id": "7fff.ac8ba9b979b5",
		"stp": false,
		"wireless": false,
		"up": true,
		"mtu": 1500,
		"qlen": 1000,
		"devtype": "bridge",
		"ipaddrs": [
			{
				"address": "REMOVED",
				"netmask": "REMOVED",
				"broadcast": "REMOVED"
			}
		],
		"ip6addrs": [
			{
				"address": "REMOVED",
				"netmask": "ffff:ffff:ffff:fff0::"
			},
			{
				"address": "REMOVED",
				"netmask": "ffff:ffff:ffff:fff0::"
			},
			{
				"address": "REMOVED",
				"netmask": "ffff:ffff:ffff:ffff::"
			}
		],
		"mac": "AC:8B:A9:B9:79:B5",
		"type": 1,
		"ifindex": 9,
		"stats": {
			"rx_bytes": 622669422,
			"tx_bytes": 347281207,
			"tx_errors": 0,
			"rx_errors": 0,
			"tx_packets": 1194145,
			"rx_packets": 3849525,
			"multicast": 2254733,
			"collisions": 0,
			"rx_dropped": 5,
			"tx_dropped": 0
		},
		"flags": {
			"up": true,
			"broadcast": true,
			"promisc": false,
			"loopback": false,
			"noarp": false,
			"multicast": true,
			"pointtopoint": false
		},
		"link": {
			"speed": 1000,
			"duplex": "unknown",
			"carrier": true,
			"changes": 2,
			"up_count": 1,
			"down_count": 1
		}
	}
}
root@Lucid-RT:~# 
```

**Comment by jasondaigo** [comment]
luci-mod-rpc was not installed. Did it now and rebooted but still no content seen on dashboard or interfaces like before. I did also reinstall the mobile app
```
Package luci-mod-rpc (25.273.68624~395e73d) installed in root is up to date.
Package rpcd-mod-luci (20240305-r1) installed in root is up to date.
Package rpcd-mod-iwinfo (2025.09.01~bba95191-r1) installed in root is up to date.
Package luci-mod-status (25.273.68624~395e73d) installed in root is up to date.
```
```
ubus list luci-rpc
luci-rpc
```
```
luci-rpc
{
        "eth1": {
                "name": "eth1",
                "wireless": false,
                "up": true,
                "mtu": 1500,
                "qlen": 1000,
                "devtype": "ethernet",
                "ipaddrs": [

                ],
                "ip6addrs": [
                        {
                                "address": "fe80::201:2eff:feac:86af",
                                "netmask": "ffff:ffff:ffff:ffff::"
                        }
                ],
                "mac": "00:01:2E:AC:86:AF",
                "type": 1,
                "ifindex": 3,
                "stats": {
                        "rx_bytes": 575189563,
                        "tx_bytes": 12130572,
                        "tx_errors": 0,
                        "rx_errors": 0,
                        "tx_packets": 121158,
                        "rx_packets": 396460,
                        "multicast": 14,
                        "collisions": 0,
                        "rx_dropped": 0,
                        "tx_dropped": 0
                },
                "flags": { 
                        "up": true,
                        "broadcast": true,
                        "promisc": false,
                        "loopback": false,
                        "noarp": false,
                        "multicast": true,
                        "pointtopoint": false
                },      
                "link": {
                        "speed": 1000,
                        "duplex": "full",
                        "carrier": true,
                        "changes": 2,
                        "up_count": 1,
                        "down_count": 1
                }
        },
        "br-lan": {     
                "name": "br-lan",
                "bridge": true,
                "ports": [
                        "eth0"
                ],
                "id": "7fff.00012eac86ae",
                "stp": false,
                "wireless": false,
                "up": true,
                "mtu": 1500,
                "qlen": 1000,
                "devtype": "bridge",
                "ipaddrs": [
                        {
                                "address": "192.168.1.1",
                                "netmask": "255.255.255.0",
                                "broadcast": "192.168.1.255"
                        }
                ],
                "ip6addrs": [
                        {
                                "address": "fd58:53d3:1a9e::1",
                                "netmask": "ffff:ffff:ffff:fff0::"
                        },
                        {
                                "address": "fe80::201:2eff:feac:86ae",
                                "netmask": "ffff:ffff:ffff:ffff::"
                        }
                ],
                "mac": "00:01:2E:AC:86:AE",
                "type": 1,
                "ifindex": 4,
                "stats": {
                        "rx_bytes": 9951140,
                        "tx_bytes": 572651709,
                        "tx_errors": 0,
                        "rx_errors": 0,
                        "tx_packets": 397654,
                        "rx_packets": 123417,
                        "multicast": 250,
                        "collisions": 0,
                        "rx_dropped": 4,
                        "tx_dropped": 0
                },
                "flags": {
                        "up": true,
                        "broadcast": true,
                        "promisc": false,
                        "loopback": false,
                        "noarp": false,
                        "multicast": true,
                        "pointtopoint": false
                },
                "link": {
                        "speed": 1000,
                        "duplex": "unknown",
                        "carrier": true,
                        "changes": 2,
                        "up_count": 1,
                        "down_count": 1
                }
        },
        "pppoe-wan": {
                "name": "pppoe-wan",
                "wireless": false,
                "up": true,
                "mtu": 1492,
                "qlen": 3,
                "devtype": "ppp",
                "ipaddrs": [
                        {
                                "address": "92.197.224.281",
                                "netmask": "255.255.255.255",
                                "remote": "211.248.213.213"
                        }
                ],
                "ip6addrs": [

                ],
                "stats": {
                        "rx_bytes": 566338903,
                        "tx_bytes": 9463866,
                        "tx_errors": 0,
                        "rx_errors": 0,
                        "tx_packets": 121098,
                        "rx_packets": 395966,
                        "multicast": 0,
                        "collisions": 0,
                        "rx_dropped": 0,
                        "tx_dropped": 0
                },
                "flags": {
                        "up": true,
                        "broadcast": false,
                        "promisc": false,
                        "loopback": false,
                        "noarp": true,
                        "multicast": true,
                        "pointtopoint": true
                },
                "link": {
                        "carrier": true,
                        "changes": 0,
                        "up_count": 0,
                        "down_count": 0
                }
        }, 
        "eth0": {
                "name": "eth0",
                "master": "br-lan",
                "wireless": false,
                "up": true,
                "mtu": 1500,
                "qlen": 1000,
                "devtype": "ethernet",
                "ipaddrs": [

                ],
                "ip6addrs": [

                ],
                "mac": "00:01:2E:AC:86:AE",
                "type": 1,
                "ifindex": 2,
                "stats": {
                        "rx_bytes": 11711941,
                        "tx_bytes": 572653102,
                        "tx_errors": 0,
                        "rx_errors": 0,
                        "tx_packets": 397660,
                        "rx_packets": 124002,
                        "multicast": 273,
                        "collisions": 0,
                        "rx_dropped": 23,
                        "tx_dropped": 0
                },
                "flags": {
                        "up": true,
                        "broadcast": true,
                        "promisc": false,
                        "loopback": false,
                        "noarp": false,
                        "multicast": true,
                        "pointtopoint": false
                },
                "link": {
                        "speed": 1000,
                        "duplex": "full",
                        "carrier": true,
                        "changes": 4,
                        "up_count": 2,
                        "down_count": 2
                }
        },
        "lo": {
                "name": "lo",
                "wireless": false,
                "up": true,
                "mtu": 65536,
                "qlen": 1000,
                "devtype": "ethernet",
                "ipaddrs": [
                        {
                                "address": "127.0.0.1",
                                "netmask": "255.0.0.0"
                        }
                ],
                "ip6addrs": [
                        {
                                "address": "::1",
                                "netmask": "ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff"
                        }
                ],
                "type": 772,
                "ifindex": 1,
                "stats": {
                        "rx_bytes": 83526,
                        "tx_bytes": 83526,
                        "tx_errors": 0,
                        "rx_errors": 0,
                        "tx_packets": 881,
                        "rx_packets": 881,
                        "multicast": 0,
                        "collisions": 0,
                        "rx_dropped": 0,
                        "tx_dropped": 0
                },
                "flags": {
                        "up": true,
                        "broadcast": false,
                        "promisc": false,
                        "loopback": true,
                        "noarp": false,
                        "multicast": false,
                        "pointtopoint": false
                },
                "link": {
                        "carrier": true,
                        "changes": 0,
                        "up_count": 0,
                        "down_count": 0
                }
        },
        "wireguard": {
                "name": "wireguard",
                "wireless": false,
                "up": true,
                "mtu": 1420,
                "qlen": 1000,
                "devtype": "wireguard",
                "ipaddrs": [
                        {
                                "address": "172.16.2.1",
                                "netmask": "255.255.255.0",
                                "remote": "172.16.2.255"
                        }
                ],
                "ip6addrs": [

                ],
                "stats": {
                        "rx_bytes": 0,
                        "tx_bytes": 0,
                        "tx_errors": 0,
                        "rx_errors": 0,
                        "tx_packets": 0,
                        "rx_packets": 0,
                        "multicast": 0,
                        "collisions": 0,
                        "rx_dropped": 0,
                        "tx_dropped": 4
                },
                "flags": {
                        "up": true,
                        "broadcast": false,
                        "promisc": false,
                        "loopback": false,
                        "noarp": true,
                        "multicast": false,
                        "pointtopoint": true
                },
                "link": {
                        "carrier": true,
                        "changes": 0,
                        "up_count": 0,
                        "down_count": 0
                }
        }
}
```

**Comment by cogwheel0** [comment]
@MrNRod @jasondaigo Try this please:

`opkg install iwinfo libiwinfo` and restart router again.

**Comment by jasondaigo** [comment]
I have these installed now with luci. Did not help.

**Comment by cogwheel0** [comment]
> I have these installed now with luci. Did not help.

I see, I'll release a patch release to fix the issue!

**Comment by rendiix** [comment]
when will the new patch be released?

**Comment by rodrigogarciana** [comment]
Same issues here.

**Comment by AfroUSApl** [comment]
I have the same problem on android 13, openwrt 24.10.5 (26.018.63408-11ffeb0)
My app dashboard and interfaces are empty. 
I have installed
luci-mod-rpc 
rpcd-mod-luci 
rpcd-mod-iwinfo 
luci-mod-status
iwinfo
But still no luck 😞🤞

![Image](https://github.com/user-attachments/assets/14a3977e-8f36-4856-a003-5ed98a501e1e)

![Image](https://github.com/user-attachments/assets/8b6df038-51b3-412e-ac6c-f4ba3ca0277c)

**Comment by wthubhub** [comment]
follow the guide still show same issue, apps version1.1.8

**Comment by natblundell** [comment]
Same problem here. Not sure how relevant it is, but my router has no WiFi.
- OpenWrt 24.10.5 r29087

```
# opkg install luci-mod-rpc rpcd-mod-luci rpcd-mod-iwinfo luci-mod-status iwinfo
Package luci-mod-rpc (26.043.84860~6cf8bf9) installed in root is up to date.
Package rpcd-mod-luci (20240305-r1) installed in root is up to date.
Package rpcd-mod-iwinfo (2025.09.01~bba95191-r1) installed in root is up to date.
Package luci-mod-status (26.043.84860~6cf8bf9) installed in root is up to date.
Unknown package 'iwinfo'.
Collected errors:
 * opkg_install_cmd: Cannot install package iwinfo.
```

**Comment by natblundell** [comment]
> Same problem here. Not sure how relevant it is, but my router has no WiFi.

It's definitely relevant. I now have a 2nd router identically configured, but with the addition of a wireless access point bridged to `br-lan`. LuCI Mobile works fine with that router.

**Comment by d687r02j8g** [comment]
I also have a device with no wireless that has this error.
I guess thats the issue then. I can't seem to see any logs for the app. Would be interesting to see why it fails.

**Comment by Cryborg12** [comment]
I am using openwrt 25.12.2 on my tp link er605 v2 router. This router does not have wireless connectivity. The dashboard and interface tabs in the app shows "connection failed" and "failed to load interfaces", respectively.

**Comment by drosmog** [comment]
I am also having the same issue. Using OpenWrt 25.12.2. All the packages listed above are installed and up to date. But like the others I also do not have Wifi on my router as it is running as a VM.

**Comment by AdvancedAssistiveTech** [comment]
> I am using openwrt 25.12.2 on my tp link er605 v2 router. This router does not have wireless connectivity. The dashboard and interface tabs in the app shows "connection failed" and "failed to load interfaces", respectively.

+1 exactly the same issue for me on OpenWrt 25.12.4 VM

**Comment by cogwheel0** [comment]
@natblundell @drosmog @rendiix @d687r02j8g @jasondaigo should now be fixed!
